"""add expense fields

Revision ID: 37907a5794eb
Revises: a501c6ea7933
Create Date: 2026-08-30 17:00:11.218216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37907a5794eb'
down_revision: Union[str, Sequence[str], None] = 'a501c6ea7933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'phone_number')
    op.drop_column('transactions', 'description')
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###
